[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "python-telegram-bot[rate-limiter]>=22.0",
    "requests>=2.32.3",
    "telegram>=0.0.1",
]
