#!/usr/bin/env python3
# Random quotes for processing messages
# Author: Created for @amkuush

import random

# List of random quotes for processing animation
QUOTES = [
    "Behind firewalls, we smile🤖.",
    "Live with no regrets.",
    "Dreams don't work unless you do.",
    "Failure is just a lesson in success",
    "Keep going🚶‍♂️; success is near.",
    "Dreams + action = success",
    "Own your story.",
    "Your vibe attracts your tribe",
    "Never stop evolving",
    "The journey is the reward",
    "Be fearless in the pursuit of you",
    "They killed Dr.Sebi he was teaching health..",
    "Everything is temporary, including this moment.",
    "Time is an illusion we all follow.",
    "Life is but a series of moments",
    "The question is the answer",
    "Reality is merely an illusion",
    "What you seek is seeking you",
    "Freedom begins where indoctrination ends",
    "To be free, you must unlearn",
    "Indoctrination replaces questions with answers",
    "Indoctrination is a quiet form of control",
    "Indoctrination silences the mind",
    "Minds controlled, freedom lost",
    "To unlearn is to be free",
    "Indoctrination kills curiosity",
    "Belief limits thought",
    "Question everything, trust no dogma",
    "Embrace the unknown",
    "Life is an adventure, make it epic",
    "Live for the moments you can't explain",
    "The world is too big to stay in one place",
    "Adventure calls, answer it",
    "The world is full of wonders",
    "The more you explore, the more you know",
    "The world is a book, explore it",
    "Say hello to my little friend!",
    "I always tell the truth",
    "Survive. Adapt. Overcome",
    "Stay alive. Win later",
    "Survival is a mindset",
    "Survive the dark. Seek light",
    "Beauty killed the beast",
    "The wound came from behind",
    "Betrayal wears a familiar face",
    "Not all enemies come from outside",
    "Built an empire, died in war",
    "Even legends meet the end",
    "Dying is part of the hunt",
    "This life is a brief journey",
    "Every action echoes in eternity",
    "Death is a doorway, not an end",
    "What we sow, we reap forever",
    "Prepare for what lasts forever",
    "Life ends, but the soul lives",
    "This world is a test",
    "Found love in prayer",
    "Only Allah never fails",
    "Allah first, always",
    "Even legends meet the end",
    "One breath at a time",
    "Depression isn't visible, but it's real",
    "Tired of pretending to be fine",
    "Broken, but still breathing",
    "Inside, it's always raining",
    "Sometimes, pain has no voice",
    "Hope whispers even in silence",
    "Don't miss me, remember me",
    "If I'm gone, let me be",
    "Live the life I couldn't",
    "Don't miss me, remember my smile",
    "Gone is just a word; live on",
    "I'm here for now, not forever",
    "If I'm gone, let me be",
    "When I'm gone, let go",
    "Don't miss me, remember me",
    "Ban me, I'll rise again",
    "They ban, we rebuild",
    "Freedom doesn't fear bans",
    "Banned today, back tomorrow",
    "Ban me once, I'll come back twice",
    "Bans don't silence the lifestyle--ªMkUsH"
]

def get_random_quote() -> str:
    """Return a random quote from the collection."""
    return random.choice(QUOTES)